spring:
  r2dbc:
    url: r2dbc:pool:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
app:
  public_routes: /login,/public/**,/version,/status,/actuator/**
jwt:
  expiration: 28800 # token expiration in seconds