spring:
  r2dbc:
    url: r2dbc:pool:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa  jpa:    show-sql: true
app:
  public_routes: /api/auth/**,/public/**,/status,/actuator/**
jwt:
  expiration: 28800 # token expiration in seconds
  shared_secret_hex: E2FB6DA4A40395B82D47EA72507F01E1679F9EAF8D31B8B3747D8D8ABF7610A8